import "./globals.css";
import Model from "../components/Modal";

export const metadata = {
  title: "Bubble",
  description: "Generated by Bubble",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className="bg-[#F5F6]">
          {children}
          <Model/>
          </body>
      </html>
  );
}
